# A unique identifier for this specific microservice in SonarCloud
sonar.projectKey=ecommerce-product-service

# The exact organization key from your SonarCloud account
sonar.organization=Abdul Rahman1727

# Tells Sonar what to scan
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.9

# Tells SonarQube where GitHub Actions will save the test coverage report
sonar.python.coverage.reportPaths=coverage.xml